import type { ExperienceProps } from "../UI/components/experience/experience";

export const experiences: ExperienceProps[] = [
  {
    position: "Senior Flutter Engineer",
    company: "IKM Digital",
    startDate: "2024",
    endDate: "PRESENT",
    description:
      "Built, maintained, and shipped high-quality Flutter applications following clean architecture, SOLID principles, and test-driven development for a range of projects — including the Spoon app, where I led a major refactor from Firebase to Supabase and migrated user data using PSQL and Python. I also built custom Dart packages to automate boilerplate generation and integrated AI coding agents into my workflow. Outside of core development, I've used Python to filter datasets and normalize text for more user-friendly experiences. In addition, I developed Typescript Edge functions to hide sensitive processes from the fontend",
    techStack: [
      "Flutter",
      "Dart",
      "Python",
      "Typrecript",
      "Javascript",
      "Supabase",
      "Firebase",
      "Clean Architecture",
      "Cursor",
      "VS Code",
      "Antigravity",
      "Play Store",
      "App Store",
    ],
    link: "https://www.linkedin.com/company/ikmdigital/posts/?feedView=all",
  },

  {
    position: "React Developer Co-op",
    company: "Freelancer",
    startDate: "April",
    endDate: "April 2026",
    description:
      "Collaborated as a mobile dev-ops developer on a cross‑platform (iOS and Android), creative-writing mobile app for Arabs, implementing Google and Apple authentication and successfully publishing the app to both the Apple App Store and Google Play Store",
    techStack: [
      "Typrdcript",
      "Supabase",
      "CSS",
      "React",
      "Capacitor",
      "Ionic",
      "Play Store",
      "App Store",
    ],
    link: "https://nass-app.com",
  },
  {
    position: "Flutter Developer Co-op",
    company: "Halaqat",
    startDate: "May 2026",
    endDate: "PRESENT",
    description:
      "Collaborated on a Flutter application that helps teachers and orginzations organize their Quran studying sessions for their students. I took part in auditing table structure generated by PDF-exporting features using standard Dart packages, with alignment with the existing development cycle and guidelines of the project.",
    techStack: ["Flutter", "Dart", "Supabase"],
    link: "https://play.google.com/store/apps/details?id=solutions.tripapps.halaqat&hl=en",
  },
  {
    position: "Senior Flutter Engineer",
    company: "Edupay",
    startDate: "Augest",
    endDate: "October 2025",
    description:
      "Collaborated with a backend engineer on a cross‑platform Flutter application that allows students and parents to access Shariah-compliant loans and discover educational institutions – architecting the entire frontend application and delivering over 60 screens – by applying clean architecture principles to ensure maintainability and scalability.",
    techStack: ["Flutter", "Dart", "pub.dev", "Clean Architecture"],
  },
  {
    position: "Flutter Developer",
    company: "Balad Bank",
    startDate: "May",
    endDate: "May 2024",
    link: "https://baladbank.net/en/home",
    description:
      "Built a currency exchange converter for Baladna Bank (Sudan) that enables SDG conversion to 9 foreign currencies – using Flutter, OCR, Dart, and Provider – delivering a reliable tool for bank operations.",

    techStack: [
      "Flutter",
      "Dart",
      "Provider",
      "Google Gemini",
      "Firebase Realtime Database",
    ],
  },
];
